### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /".*(?<!/\)"/: Invalid group

### ISSUE THREAD

**Issue by jbsathler** [foreshadow/atom-minify-stand-alone#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-minify-stand-alone](https://github.com/foreshadow/atom-minify-stand-alone) package 0.2.0

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /".*(?<!\\)"/: Invalid group

```
At C:\Users\Jaderson\.atom\packages\atom-minify-stand-alone\lib\atom-minify-stand-alone.js:54

SyntaxError: Invalid regular expression: /".*(?<!\\)"/: Invalid group
    at compressjs (/packages/atom-minify-stand-alone/lib/atom-minify-stand-alone.js:54:21)
    at /packages/atom-minify-stand-alone/lib/atom-minify-stand-alone.js:103:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -7:06.1.0 editor:move-to-first-character-of-line (input.hidden-input)
  4x -7:05.8.0 core:move-right (input.hidden-input)
     -7:05.0 core:delete (input.hidden-input)
     -6:27.1.0 find-and-replace:show (input.hidden-input)
     -6:22.1.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -6:21.9.0 core:delete (input.hidden-input)
     -5:32.2.0 core:save (input.hidden-input)
     -3:04.4.0 core:backspace (input.hidden-input)
     -3:02.3.0 core:confirm (input.hidden-input)
     -2:37.8.0 editor:consolidate-selections (input.hidden-input)
     -2:37.8.0 core:cancel (input.hidden-input)
     -2:37.8.0 editor:consolidate-selections (input.hidden-input)
     -2:37.8.0 core:cancel (input.hidden-input)
  4x -2:30.8.0 core:backspace (input.hidden-input)
     -1:50.4.0 core:confirm (input.hidden-input)
     -0:27.9.0 Minify stand alone: generate (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-minify-stand-alone 0.2.0 
atom-ternjs 0.17.2 
atom-yii2 0.4.0 
autocomplete-ionic-framework 0.2.2 
column-select 0.2.0 
git-control 0.8.2 
ionic-framework-snippets 1.2.1 
ionic-preview 0.7.0 
jquery-snippets 11.0.0 
language-asp 1.0.0 
language-twig 1.6.3 
meteor-api 2.20.0 
minimap 4.26.8 
symfony-snippets 0.3.0 
```

**Comment by foreshadow** [comment]
I may not be maintaining this package for months.
